spring:
  application:
    name: DiscoveryService
server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    fetch-registry: false
    register-with-eureka: false
